### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "second_db" does not exist

### ISSUE THREAD

**Issue by tilo** [rgeo/activerecord-postgis-adapter#130]
I'm connecting to two PostgreSQL databases in my Rails 4.1 app:
- the first DB is used for most models and is PostGIS
- the second DB is used only for a few models, and does not have the PostGIS extension

```
class SecondDB < ActiveRecord::Base
  establish_connection :second_db
end

class Something < SecondDB
  self.table_name = :something
  self.primary_key = :link_id
end

# rails c
> x = Something.last
#<Something link_id: 1022331210, seq_num: 999999, lat: 3369603, lon: -11786433, z_coord: nil, zlevel: 0> 

1.9.3-p448 :003 > x.seq_num
PG::UndefinedTable: ERROR:  relation "second_db" does not exist
LINE 5:                WHERE a.attrelid = '"second_db"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"second_db"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "second_db" does not exist
LINE 5:                WHERE a.attrelid = '"second_db"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"second_db"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:815:in `async_exec'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:815:in `block in exec_no_cache'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:815:in `exec_no_cache'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:969:in `column_definitions'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:187:in `columns'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/connection_adapters/schema_cache.rb:93:in `block in prepare_default_proc'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/connection_adapters/schema_cache.rb:44:in `yield'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/connection_adapters/schema_cache.rb:44:in `default'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/connection_adapters/schema_cache.rb:44:in `columns'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/composite_primary_keys-7.0.2/lib/composite_primary_keys/model_schema.rb:5:in `columns'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/model_schema.rb:260:in `column_names'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/attribute_methods.rb:74:in `block in define_attribute_methods'
               from <internal:prelude>:10:in `synchronize'
               from ./.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/mutex_m.rb:62:in `mu_synchronize'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/attribute_methods.rb:71:in `define_attribute_methods'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/attribute_methods.rb:73:in `block in define_attribute_methods'
               from <internal:prelude>:10:in `synchronize'
               from ./.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/mutex_m.rb:62:in `mu_synchronize'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/attribute_methods.rb:71:in `define_attribute_methods'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/activerecord-4.1.1/lib/active_record/attribute_methods.rb:195:in `method_missing'
               from (irb):3
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/railties-4.1.1/lib/rails/commands/console.rb:90:in `start'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/railties-4.1.1/lib/rails/commands/console.rb:9:in `start'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:69:in `console'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
               from ./.rvm/gems/ruby-1.9.3-p448@myproject/gems/railties-4.1.1/lib/rails/commands.rb:17:in `<top (required)>'
               from bin/rails:8:in `require'
               from bin/rails:8:in `<main>'1.9.3-p448 :004 > ActiveRecord::Base.connection.schema_names
 => ["public", "topology"]
1.9.3-p448 :005 > SecondDB.connection.schema_names
 => ["public"]
```

**Comment by shettarvinay** [comment]
Hey @tilo any fix you found for this ?. Stuck with same issue, feels like establish_connection is overriding the default connection. BTW am on Rails5 and postgress.

**Comment by keithdoggett** [comment]
I was able to get this to work with the current version (6.0.1) with the following setup. I'm running Rails 6 as well.

```yml
# config/database.yml
default: &default
  adapter: postgis
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: password

development:
  primary:
    <<: *default
    database: postgis-adapter-test_dev
  second_db:
    <<: *default
    adapter: postgresql
    database: postgis-adapter-test-second-db_dev
    username: postgres
    migrations_paths: db/second_db_migrate
```

```rb
# db/second_db_migrate/20201127_create_widgets.rb
class CreateWidgets < ActiveRecord::Migration[6.0]
  def change
    create_table :widgets do |t|
      t.string :name
      t.timestamps
    end
  end
end
```

```rb
# app/models/second_db.rb
class SecondDb < ApplicationRecord
  self.abstract_class = true

  connects_to database: { writing: :second_db, reading: :second_db }
end
```

```rb
# app/models/widget.rb
class Widget < SecondDb
end
```

If this doesn't fix the issue please re-open this.
