### ISSUE TITLE
Incompatibility with schema_plus: Error "column does not exist" on geometry column index creation

### ISSUE THREAD

**Issue by dealbase** [rgeo/activerecord-postgis-adapter#155]
When using schema_plus gem and have an index defined on a non-geographic spatial column, db:schema:load errors with "column does not exist" when creating the index. Schema_plus dumps the index inline, and the schema_plus adapter tries to create the index before the column has been created by ActiveRecord::ConnectionAdapters::PostGISAdapter::MainAdapter.

For example:

```
  create_table "samples", force: true do |t|
    t.spatial  "geom",                        limit: {:srid=>4326, :type=>"point"}
    t.index ["geom"], :name => "idx_samples_geom", spatial: true
  end
```

`rake db:schema:load` will error with:

```
-- create_table("samples":force=>true})
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "geom" does not exist
: CREATE  INDEX  "idx_samples_geom" ON "samples" USING GIST ("geom")
 /gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `async_exec'
 /gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `block in execute'
 /gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
 /gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
 /gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
  /gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:127:in `execute'
/work/activerecord-postgis-adapter/lib/active_record/connection_adapters/postgis_adapter/main_adapter.rb:167:in `add_index'
  /gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:206:in `block in create_table'
  /gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:206:in `each_pair'
  /gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:206:in `create_table'
  /gems/schema_plus-1.7.1/lib/schema_plus/active_record/connection_adapters/schema_statements.rb:38:in `create_table_with_schema_plus'
/work/activerecord-postgis-adapter/lib/active_record/connection_adapters/postgis_adapter/main_adapter.rb:117:in `create_table'
  /gems/activerecord-4.1.1/lib/active_record/migration.rb:649:in `block in method_missing'
  /gems/activerecord-4.1.1/lib/active_record/migration.rb:621:in `block in say_with_time'
  /gems/activerecord-4.1.1/lib/active_record/migration.rb:621:in `say_with_time'
  /gems/activerecord-4.1.1/lib/active_record/migration.rb:641:in `method_missing'
/work/samples/db/schema.rb:368:in `block in <top (required)>'
```

MainAdapter.create_table calls super, and that errors before getting to the `table_definition.non_geographic_spatial_columns` iterator that creates the non-geographic spatial columns.

lines 113-135 (relevant lines # HIGHLIGHTED IN CAPS):

```
        def create_table(table_name, options = {}, &block)
          table_name = table_name.to_s
          # Call super and snag the table definition
          table_definition = nil
          super(table_name, options) do |td|  # ERRORS CREATING INDEX HERE
            block.call(td) if block
            table_definition = td
          end
          table_definition.non_geographic_spatial_columns.each do |col|
            options = {
              default: col.default,
              has_m: col.has_m?,
              has_z: col.has_z?,
              null: col.null,
              srid:  col.srid,
              type:  col.spatial_type,
            }
            column_name = col.name.to_s
            type = col.spatial_type

            add_spatial_column(table_name, column_name, type, options)  # CREATES COLUMN HERE
          end
        end
```

**Comment by teeparham** [comment]
This is a schema plus problem.
