### ISSUE TITLE
Undefined method 'st_point'

### ISSUE THREAD

**Issue by h0lyalg0rithm** [rgeo/activerecord-postgis-adapter#174]
Hi I am currently using the beta release of this gem and I came across this issue when running the migration.
I am using '3.0.0beta2'
Ruby 2.2
ActiveRecord 4.2

**Comment by sauy7** [comment]
@h0lyalg0rithm looks like a misconfiguration somewhere in your app. Some things to check...

Are you sure the postgis extension has been created in the database (rake db:gis:setup)?

Is the postgis adapter specified in your database.yml file?

Does this gem appear in your Gemfile.lock?

**Comment by h0lyalg0rithm** [comment]
here is my database.yml file
```
default: &default
  adapter: postgis
  encoding: unicode
  schema_search_path: public, postgis
```
I have the beta version of the gem in my gemfile
```gem 'activerecord-postgis-adapter', '3.0.0beta2' ```

**Comment by sauy7** [comment]
Are you able to run an SQL command including postgis functions directly on your database?

For instance, what does the following return:

SELECT PostGIS_full_version();

Does your database include the spatial_ref_sys table?

**Comment by h0lyalg0rithm** [comment]
Yes the database contains the spatial_ref_sys table;

I was able to run postgis function.I guess there is some issue creating the schema file for the database.My current workaround is to manually specify the datatype in the schema file and then load it into the database.
In my case i set it as
``` t.geography "latlon",                limit: {:srid=>4326, :type=>"point", :geographic=>true}```

SELECT PostGIS_full_version(); gave me the following result
```
                                                                       postgis_full_version
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="2.1.7 r13414" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.11.2, released 2015/02/10" LIBXML="2.9.2" LIBJSON="UNKNOWN" RASTER
(1 row)
```

**Comment by sauy7** [comment]
Personally, I'm using this in the migration file:

    t.st_point :lonlat, srid: 4326, geographic: true

and in config/application:

    config.active_record.schema_format = :sql

So I have a structure.sql file rather than schema.rb.

**Comment by h0lyalg0rithm** [comment]
It seems like the issue occurs only when you try to add the st_point migration to an existing model.
IF you add it to a create_table block there are no problems.
But if you add the code in the change_table block you get the following error
```
undefined method `st_point' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::Table:0x007fd0a55177c8>/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/rgeo-activerecord-2.1.1/lib/rgeo/active_record/common_adapter_elements.rb:87:in `method_missing_with_rgeo'
/Users/surajshirvankar/Google Drive/Development/Apps/postgis/db/migrate/20150423200401_addpost.rb:4:in `block in change'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:351:in `change_table'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/Users/surajshirvankar/Google Drive/Development/Apps/postgis/db/migrate/20150423200401_addpost.rb:3:in `change'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:606:in `exec_migration'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
NoMethodError: undefined method `st_point' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::Table:0x007fd0a55177c8>
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/rgeo-activerecord-2.1.1/lib/rgeo/active_record/common_adapter_elements.rb:87:in `method_missing_with_rgeo'
/Users/surajshirvankar/Google Drive/Development/Apps/postgis/db/migrate/20150423200401_addpost.rb:4:in `block in change'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:351:in `change_table'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/Users/surajshirvankar/Google Drive/Development/Apps/postgis/db/migrate/20150423200401_addpost.rb:3:in `change'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:606:in `exec_migration'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/surajshirvankar/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by teeparham** [comment]
You do not have to change the column if you are updating to the 3.0.0 adapter. You may need to run `rake db:schema:dump` to re-dump the schema file in the new format.

The column definition generated for the ruby schema file is (usually) different than what you specify in the migrations because there are several ways to define a column, and the "limit" options are need to import the column definition.

However, this is likely bug. We need a test for `change_column`.

**Comment by zaidakram** [comment]
I second @h0lyalg0rithm on this. I'm facing the same issue. This issue occurs only when you try to add the st_point migration to an existing model.

```
undefined method `st_point' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::Table:0x007fdf0c2c8268>/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/rgeo-activerecord-3.0.0/lib/rgeo/active_record/common_adapter_elements.rb:87:in `method_missing_with_rgeo'
/home/zaid/workspace/myproject/db/migrate/20150523084650_add_coordinates_to_property.rb:4:in `block in change'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:351:in `change_table'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/home/zaid/workspace/myproject/db/migrate/20150523084650_add_coordinates_to_property.rb:3:in `change'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:606:in `exec_migration'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `ddl_transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
NoMethodError: undefined method `st_point' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::Table:0x007fdf0c2c8268>
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/rgeo-activerecord-3.0.0/lib/rgeo/active_record/common_adapter_elements.rb:87:in `method_missing_with_rgeo'
/home/zaid/workspace/myproject/db/migrate/20150523084650_add_coordinates_to_property.rb:4:in `block in change'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:351:in `change_table'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/home/zaid/workspace/myproject/db/migrate/20150523084650_add_coordinates_to_property.rb:3:in `change'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:606:in `exec_migration'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:1041:in `ddl_transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/zaid/.rvm/gems/ruby-2.2.0@mygemset/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
```

**Comment by mr-teu** [comment]
I am still having this issue when creating an ST_point column lonlat in the table addresses: 

PG::UndefinedObject: ERROR:  type "st_point" does not exist
LINE 1: ALTER TABLE "addresses" ADD "lonlat" st_point

**Comment by MaxPleaner** [comment]
Having this problem _in my test environment only_. It's working in development mode. 

running `bundle exec rake db:migrate RAILS_ENV=test` - 

```txt
undefined method `st_point' for
#<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x0055cdd8f278e8>
```

Here's the Gemfile.lock:

    activerecord (4.2.7.1)
    activerecord-postgis-adapter (3.1.4)

I added the enable_extension line, my database adapter is specified as postgis, and I've confirmed the PostGIS_version is set.

This isn't just caused by adding to an existing model, as suggested here: https://github.com/rgeo/activerecord-postgis-adapter/issues/174. Here's the migration in question:

```rb
class CreateLocations < ActiveRecord::Migration
  def change
    enable_extension "postgis"
    create_table :locations do |t|
      t.text :street
      t.text :city
      t.text :state
      t.string :zipcode
      t.string :country
      t.decimal :latitude
      t.decimal :longitude
      t.st_point :geom, geographic: true, srid: 4326, dimension: 2
      t.text :other
      t.timestamps
    end
    add_index :locations, :applicant_id, unique: true
  end
end
```

**Comment by jcquarto** [comment]
How did you fix your DATABASE_URL ?  It sounds simple enough but I'm not quite sure where you are fixing it.

Our own situation:  everything works fine in development. When we push to production, on Heroku, we get the error this thread refers to.    Note that in heroku's "postdeploy" stage, we do
`bundle exec rails db:gis:setup`
`bundle exec rails db:migrate`

**Comment by MaxPleaner** [comment]
@jcquarto it was a matter of changing out `postgres://` for `postgis://` in the database url. On Heroku you don't set the url yourself so I don't think that's the right fix. Maybe check Heroku's articles about postgis; wish I could be of more help.

**Comment by h0lyalg0rithm** [comment]
@jcquarto I had the same issue, changed the uri from `postgres` to `postgis`

**Comment by pejrich** [comment]
@h0lyalg0rithm How did you change the uri on heroku? It wont let me change it as an env var

**Comment by h0lyalg0rithm** [comment]
@pejrich You can change the uri  in the settings of the dyno.Click on the reveal config vars and the change it the database url from postgres to postgis

**Comment by chrisfinne** [comment]
For proper Heroku config, this article tells you to tweak your `database.yml`:
https://devcenter.heroku.com/articles/rails-database-connection-behavior

```
production:
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>
```

**Comment by jenyeeiam** [comment]
Holy shit you saved me! @chrisfinne !!
