### ISSUE TITLE
Migration to rails 4.2.2 - postgis 3.0.0 NoMethodError: undefined method `point' for nil:NilClass

### ISSUE THREAD

**Issue by dcdieci** [rgeo/activerecord-postgis-adapter#186]
Hi,
I am not entirely sure if the problem is related to regeo or the adapter.
I just updated to rails 4.2.2 and also to activerecord-postgis-adapter (3.0.0).
Since then I get the following error on my model which has a column called centroid.

schema.rb
    t.spatial  "centroid",            limit: {:srid=>0, :type=>"point"}

initializer
config.register(RGeo::Geographic.spherical_factory(srid: 4326), geo_type: "centroid")

The following error occurs:
NoMethodError: undefined method `point' for nil:NilClass
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/rgeo-0.3.20/lib/rgeo/wkrep/wkb_parser.rb:227:in `_parse_object'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/rgeo-0.3.20/lib/rgeo/wkrep/wkb_parser.rb:158:in `parse'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/activerecord-postgis-adapter-3.0.0/lib/active_record/connection_adapters/postgis/oid/spatial.rb:102:in `parse_wkt'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/activerecord-postgis-adapter-3.0.0/lib/active_record/connection_adapters/postgis/oid/spatial.rb:90:in `type_cast'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/type/value.rb:23:in `type_cast_from_database'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/attribute.rb:104:in `type_cast'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/attribute.rb:42:in `original_value'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/attribute.rb:37:in `value'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/attribute_set.rb:31:in `fetch_value'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/attribute_methods/read.rb:93:in `_read_attribute'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/attribute_methods/read.rb:87:in `read_attribute'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/attribute_methods.rb:305:in `attribute_for_inspect'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/core.rb:444:in `block in inspect'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/core.rb:442:in `collect'
	from /Users/dc/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.2/lib/active_record/core.rb:442:in `inspect'
	from (irb):4

in the rgeo wkb_parser.rb line 216 I see that @cur_factory  is nil

@cur_factory = @factory_generator.call(:srid => @cur_srid, :has_z_coordinate => has_z_, :has_m_coordinate => has_m_)

because if_supported? in line 233 of interface.rb returns nil

      # Returns true if any GEOS implementation is supported.
      # If this returns false, GEOS features are not available at all.

      def supported?
        FFI_SUPPORTED || CAPI_SUPPORTED
      end

So the question is how does it come that i get false in here after the upgrade?
Help is highly appreciated. Thanks in advance

**Comment by dcdieci** [comment]
So the issue is not related to the postgres adatpter, it resides in rgeo.
After the upgrade of rgeo I had to install the GEOS lib.
For me installing geos via brew fixed the issue 
brew install geos
