### ISSUE TITLE
PostgreSQL adapter used instead of Postgis: undefined method `geometry' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x00000005181668>

### ISSUE THREAD

**Issue by sgrubsmyon** [rgeo/activerecord-postgis-adapter#234]
Hi,

I'm facing the problem that I cannot get Rails to use the activerecord-postgis-adapter, even though the `config/database.yml` has `adapter: postgis` set.

The problem does not appear on a fresh Ubuntu 16.04 LTS install with the `apt-get` installed Ruby from the Ubuntu package management. But when I install Ruby using `rvm`, then the problem appears (for both Rails version 4.2.6 and 5.0.0.1) and after removing `rvm` again and re-installing the Ubuntu Ruby, the problem persists.

Error message is:
```
$ ./bin/rake db:migrate
Running via Spring preloader in process 24322
== 20160922095221 CreateSpatials: migrating ===================================
-- create_table(:spatials)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `geometry' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x00000005181668>
/home/mvoge/ena_test/db/migrate/20160922095221_create_spatials.rb:5:in `block in change'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:277:in `create_table'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:845:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:814:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:814:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:834:in `method_missing'
/home/mvoge/ena_test/db/migrate/20160922095221_create_spatials.rb:3:in `change'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:788:in `exec_migration'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:772:in `block (2 levels) in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:771:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:770:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:950:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1211:in `block in execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1279:in `block in ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1279:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1210:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1183:in `block in migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1182:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1182:in `migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1131:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1298:in `with_advisory_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1131:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1005:in `up'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:983:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/var/lib/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
-e:1:in `<main>'
NoMethodError: undefined method `geometry' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x00000005181668>
/home/mvoge/ena_test/db/migrate/20160922095221_create_spatials.rb:5:in `block in change'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:277:in `create_table'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:845:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:814:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:814:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:834:in `method_missing'
/home/mvoge/ena_test/db/migrate/20160922095221_create_spatials.rb:3:in `change'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:788:in `exec_migration'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:772:in `block (2 levels) in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:771:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:770:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:950:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1211:in `block in execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1279:in `block in ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1279:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1210:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1183:in `block in migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1182:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1182:in `migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1131:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1298:in `with_advisory_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1131:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:1005:in `up'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:983:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/var/lib/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
This means that Rails is using the wrong adapter, the PostgreSQL adapter, and not the Postgis adapter. It is totally intransparent to me why this happens and if I can somehow force the Postgis adapter to be used.

Any more insight on how the adapter is chosen and why the wrong adapter might be picked up is appreciated.

See below for details and steps to reproduce the problem.

This appears to be the same issue as reported here: https://stackoverflow.com/questions/37421864/undefined-method-geometry-for-activerecordconnectionadapterspostgresql

# Working setup

Using the following steps in a fresh Ubuntu 16.04 LTS works without error:

1: Install postgres
```
sudo apt-get install postgresql-9.5 postgis libpq-dev
sudo -u postgres createuser -P -d myuser
```

2: Change user's role to superuser, so she can create the postgis extension with `rake db:create`
```
sudo -u postgres psql
> ALTER ROLE myuser SUPERUSER;
```

3a: Install ruby from ubuntu repo
```
sudo apt-get install ruby ruby-dev build-essential zlib1g-dev
sudo gem install rails
```

4: Install JavaScript engine
```
sudo apt-get install nodejs
```

5: Initialize Rails app
```
mkdir test
cd test
rails new . --database=postgresql
```

### Gemfile:
```ruby
# add:
gem 'activerecord-postgis-adapter'
```

6: Install gem
```
./bin/bundle install
```

### config/database.yml:
```yaml
default: &default
  adapter: postgis
  encoding: unicode
  pool: 5
  username: myuser
  password: MySecretPassword
  host: localhost
# (rest of the file left untouched)
```

7: Create migration
```
./bin/rake db:create
./bin/rails g model Spatial name:string geodata:geometry
./bin/rake db:migrate
```

# Steps to reproduce the problem

After installing a fresh Ubuntu 16.04 LTS, replace step 3a from above with:

3b: Install Ruby through rvm (taken from https://gorails.com/setup/ubuntu/16.04)
```
sudo apt-get update
sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev
sudo apt-get install libgdbm-dev libncurses5-dev automake libtool bison libffi-dev
gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
rvm install 2.3.1
rvm use 2.3.1 --default
gem install bundler
gem install rails
```

It does not make a difference if I use `gem install rails -v 4.2.6` in the above step (i.e. force version 4.2.6 instead of using current version, at the moment 5.0.0.1), so it's not a version compatibility issue.

The rest of the steps are identical and the problem appears.

After removing rvm by deleting all lines containing "rvm" from the relevant `~/.*` files and doing `rm -rf ~/.rvm`, then installing the Ubuntu ruby again as in step 3a, the same problem still appears, even though the system should be as before using rvm.

It seems that something in the system is altered, but I don't know what.

I suspected that some information in the PostgreSQL install is stored, so I purged (`sudo apt-get purge`) all the installed postgres and ruby Ubuntu packages and installed again. I should have a system as it is after the fresh OS install. But the problem still persists.

# Closing remarks

The problem surfaced when trying to deploy my app to an Ubuntu 14.04 server with Capistrano. I followed the tutorial https://gorails.com/deploy/ubuntu/14.04, where it was recommended to use a virtual environment Ruby, such as `rbenv` or `rvm`.

I used `rbenv` with Capistrano and the same problem appeared. Strangely, on my development system, where I never installed rvm or rbenv, the problem appeared as well after installing gems `capistrano`, `capistrano-bundler`, `capistrano-rails`, and `capistrano-rbenv`, and after executing `cap production deploy`.

Please tell me if more debugging info is required and how I can deliver it.
Thanks.

**Comment by sgrubsmyon** [comment]
Surprisingly, it seems that using a database URL with protocol specification `postgis` fixes the issue and the correct ActiveRecord adapter is selected. E.g. in the `config/database.yml`:
```yaml
default: &default
  adapter: postgis
  encoding: unicode
  pool: 5
  url: postgis://myuser:MySecretPassword@localhost
```
This is the workaround that solves the issue for me. However, I have no idea what happens behind the curtains.
